# This file was generated by GoReleaser. DO NOT EDIT.
cask "policy-bot-tests" do
  desc ""
  homepage ""
  version "0.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "policy-bot-tests"

  on_macos do
    on_intel do
      url "https://github.com/reegnz/policy-bot-tests/releases/download/v0.5.2/policy-bot-tests_Darwin_x86_64.tar.gz"
      sha256 "264bbfdc6ddc30f6539784b71575b8c8d7146f9a490197e22c00fe023065583f"
    end
    on_arm do
      url "https://github.com/reegnz/policy-bot-tests/releases/download/v0.5.2/policy-bot-tests_Darwin_arm64.tar.gz"
      sha256 "d5e1fcba8b6ed8b46ec50bfa6ac2c6cd3ce59c8fa0c67bed25f88cb401d02717"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/reegnz/policy-bot-tests/releases/download/v0.5.2/policy-bot-tests_Linux_x86_64.tar.gz"
      sha256 "0c047c405d6e35b03093ff8068331f79ec50e0957057307b1f61619a22418b37"
    end
    on_arm do
      url "https://github.com/reegnz/policy-bot-tests/releases/download/v0.5.2/policy-bot-tests_Linux_arm64.tar.gz"
      sha256 "8096f53671848f58a84d46ff4b5ff2e63c559e7d94292aac4c04109e3e9654f7"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/policy-bot-tests"]
    end
  end

  # No zap stanza required
end
