# This file was generated by GoReleaser. DO NOT EDIT.
cask "policy-bot-tests" do
  desc ""
  homepage ""
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "policy-bot-tests"

  on_macos do
    on_intel do
      url "https://github.com/reegnz/policy-bot-tests/releases/download/v0.5.1/policy-bot-tests_Darwin_x86_64.tar.gz"
      sha256 "cd561702d7a29549f75d5aaa51d19fa71f6a852a55a841db5f9e89d1a3d8da75"
    end
    on_arm do
      url "https://github.com/reegnz/policy-bot-tests/releases/download/v0.5.1/policy-bot-tests_Darwin_arm64.tar.gz"
      sha256 "e3fbe423870cb0eb42200f0093467ca3a9474786f784104a57b986301c3a785d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/reegnz/policy-bot-tests/releases/download/v0.5.1/policy-bot-tests_Linux_x86_64.tar.gz"
      sha256 "3dee942e49ff9158969b9231cb349c9441d167ef02f13551feb722988533066b"
    end
    on_arm do
      url "https://github.com/reegnz/policy-bot-tests/releases/download/v0.5.1/policy-bot-tests_Linux_arm64.tar.gz"
      sha256 "aa6511764b5c22e5928891c51fe29031e02eeafa2e45cefd2c3ffd2407092344"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/policy-bot-tests"]
    end
  end

  # No zap stanza required
end
