# This file was generated by GoReleaser. DO NOT EDIT.
cask "policy-bot-tests" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "8aa0e40aa63b014649fd8fea5d900056babe75613566cc11988d78bc6ae319ed"
      url "https://github.com/reegnz/policy-bot-tests/releases/download/v#{version}/policy-bot-tests_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cccbc2a64f2b58dd62d7d0a00b88e3a636a30fe622413d1628e9ae61a3f3733a"
      url "https://github.com/reegnz/policy-bot-tests/releases/download/v#{version}/policy-bot-tests_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6ce2bfc3c323017f810ad0792171b9c11b053facbb41c38b6d39bb1c7d97a234"
      url "https://github.com/reegnz/policy-bot-tests/releases/download/v#{version}/policy-bot-tests_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "780b8f9e36c5ae5827fad99d2b12bac0c4092e69ade1d9b043dc108b734f4006"
      url "https://github.com/reegnz/policy-bot-tests/releases/download/v#{version}/policy-bot-tests_Linux_x86_64.tar.gz"
    end
  end

  name "policy-bot-tests"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "policy-bot-tests"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/policy-bot-tests"]
    end
  end

  # No zap stanza required
end
